name: OCR Pipeline Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Docker dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t ocr .

      - name: Run OCR pipeline
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -e GIT_PYTHON_REFRESH=quiet ocr

      - name: Check OCR output exists
        run: ls -lh ocr_output.txt

      - name: Upload OCR output artifact
        uses: actions/upload-artifact@v3
        with:
          name: ocr_output
          path: ocr_output.txt
